import{parse,parseEditedLine,renderLine}from'./parser.js';import{png}from'./exporter.js';
const $=s=>document.querySelector(s);let state={mode:'assistant',lines:[]};let generated='';
function build(){state=parse($('#source').value,$('#mode').value,$('#self').value.trim());$('#detected').textContent=`Detected: ${state.mode.toUpperCase()} · ${state.lines.length} lines`;people();messages();rpTypes();regenerate()}
function people(){let ps=[...new Set(state.lines.flatMap(x=>x.people||[]).filter(Boolean))].sort();$('#people').innerHTML=ps.length?ps.map(p=>`<label class="chip"><input type="checkbox" data-person="${esc(p)}" checked> ${p}</label>`).join('\n'):'<span class="muted">No characters detected.</span>';$('#people').querySelectorAll('input').forEach(x=>x.onchange=regenerate)}
function messages(){let box=$('#messages'),ms=[...new Set(state.lines.map(x=>x.messagePerson).filter(Boolean))].sort();box.innerHTML=ms.length?`<div class="filtertitle">Messages</div><div class="chips"><label class="chip"><input type="checkbox" id="allmessages"> All messages</label>${ms.map(p=>`<label class="chip"><input type="checkbox" data-message-person="${esc(p)}"> ${p}</label>`).join('\n')}</div>`:'';if(!ms.length)return;let all=$('#allmessages'),items=[...box.querySelectorAll('[data-message-person]')];all.onchange=()=>{items.forEach(x=>x.checked=all.checked);regenerate()};items.forEach(x=>x.onchange=()=>{all.checked=items.every(y=>y.checked);regenerate()})}
function rpTypes(){$('#rptypes').innerHTML=`<div class="filtertitle">RP Type</div><div class="chips"><label class="chip"><input type="checkbox" id="inperson" checked> In-person RP</label><label class="chip"><input type="checkbox" id="phonecalls" checked> Phone calls</label></div>`;$('#inperson').onchange=regenerate;$('#phonecalls').onchange=regenerate}
function esc(s){return s.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;')}
function allowed(l){let f=$('#from').value,t=$('#to').value;if(f&&l.ts&&l.ts<f)return false;if(t&&l.ts&&l.ts>t)return false;if(l.type==='ooc')return $('#ooc').checked;if(l.type==='system')return $('#system').checked;if(l.type==='message'){let selected=[...document.querySelectorAll('[data-message-person]:checked')].map(x=>x.dataset.messagePerson);return !!l.messagePerson&&selected.includes(l.messagePerson)}if((l.type==='speech'||l.type==='emote')&&l.phoneRP&&!$('#phonecalls')?.checked)return false;if((l.type==='speech'||l.type==='emote')&&!l.phoneRP&&!$('#inperson')?.checked)return false;let inputs=[...document.querySelectorAll('[data-person]')],selected=inputs.filter(x=>x.checked).map(x=>x.dataset.person);if(inputs.length&&!(l.people||[]).some(p=>selected.includes(p)))return false;return true}
function regenerate(){let lines=state.lines.filter(allowed);generated=lines.map(l=>l.raw).join('\n');$('#filtered').value=generated;$('#editstatus').textContent='';preview()}
function preview(){let raw=$('#filtered').value,lines=raw.replace(/\r/g,'').split('\n').filter(x=>x.trim()).map(x=>parseEditedLine(x,state.mode,$('#self').value.trim())),p=$('#preview');p.innerHTML='';p.style.maxWidth=$('#width').value+'px';p.style.padding=$('#chatbg').checked?'8px':'0';p.style.background=$('#chatbg').checked?'rgba(0,0,0,.45)':'transparent';lines.forEach(l=>{let d=document.createElement('div');d.className='chat';d.style.fontSize=$('#font').value+'px';if($('#timestamps').checked&&l.ts){let s=document.createElement('span');s.className='ts';s.textContent=`[${l.ts}] `;d.appendChild(s)}renderLine(l,state.mode,$('#self').value.trim()).forEach(g=>{let s=document.createElement('span');s.style.color=g.color;s.textContent=g.text;d.appendChild(s)});p.appendChild(d)});$('#stats').textContent=`${lines.length} lines`;$('#editstatus').textContent=raw===generated?'':'Edited'}
function exportLines(){return $('#filtered').value.replace(/\r/g,'').split('\n').filter(x=>x.trim()).map(x=>{let l=parseEditedLine(x,state.mode,$('#self').value.trim());return{...l,selected:true,visible:true,edited:l.body,original:l.body}})}
$('#build').onclick=build;['ooc','system','from','to'].forEach(id=>$('#'+id).onchange=regenerate);$('#filtered').oninput=preview;['font','width','timestamps','chatbg'].forEach(id=>$('#'+id).oninput=()=>{$('#fontv').textContent=$('#font').value;preview()});$('#copy').onclick=async()=>navigator.clipboard.writeText($('#filtered').value);$('#resetedit').onclick=()=>{$('#filtered').value=generated;preview()};$('#png').onclick=()=>png(exportLines(),{font:$('#font').value,width:$('#width').value,timestamps:$('#timestamps').checked,bg:$('#chatbg').checked},l=>renderLine(l,state.mode,$('#self').value.trim()));$('#clear').onclick=()=>{$('#source').value='';$('#filtered').value='';state={mode:'assistant',lines:[]};generated='';$('#people').innerHTML='<span class="muted">No characters detected.</span>';$('#messages').innerHTML='';$('#rptypes').innerHTML='';$('#preview').innerHTML='';$('#stats').textContent='';$('#detected').textContent='Waiting for a chatlog.'};$('#sample').onclick=()=>{$('#source').value=`[20:55:03] ~y~Marisol Lopez says (phone): Zohan?\n[20:55:59] (Phone) * Marisol Lopez has a broken tone of voice.\n[20:57:02] !{#C2A2DA}* Marisol Lopez pinches Jovan’s side.\n[20:57:09] !{#5F5F5F}Marisol Lopez says [low]: Or what?\n[20:57:20] !{#F0F0F0}Jovan Tomic says [low]: I didn't mean that, baby girl, princess.`;$('#mode').value='auto';$('#self').value='Jovan Tomic';build()};