import{parse,recolor}from'./parser.js';import{snapshot,restore,move}from'./scene-builder.js';import{save,load}from'./storage.js';import{png}from'./exporter.js';
const $=s=>document.querySelector(s);let state={mode:'assistant',lines:[]},undo=[],redo=[],dragId=null;
function hist(){undo.push(snapshot(state.lines));if(undo.length>50)undo.shift();redo=[]}
function opts(){return{font:$('#font').value,width:$('#width').value,timestamps:$('#timestamps').checked,bg:$('#chatbg').checked}}
function build(){state=parse($('#source').value,$('#mode').value,$('#self').value.trim());undo=[];redo=[];$('#detected').textContent=`Detected: ${state.mode.toUpperCase()} · ${state.lines.length} lines`;people();filter()}
function people(){let ps=[...new Set(state.lines.flatMap(x=>x.people||[]).filter(Boolean))].sort();$('#people').innerHTML=ps.length?ps.map(p=>`<label class="chip"><input type="checkbox" data-person="${p.replace(/"/g,'&quot;')}" checked> ${p}</label>`).join(''):'<span class="muted">No characters detected.</span>';$('#people').querySelectorAll('input').forEach(x=>x.onchange=filter)}
function allowed(l){let f=$('#from').value,t=$('#to').value;if(f&&l.ts&&l.ts<f)return false;if(t&&l.ts&&l.ts>t)return false;if(l.type==='ooc'&&!$('#ooc').checked)return false;if(l.type==='system'&&!$('#system').checked)return false;let inputs=[...$('#people').querySelectorAll('input[data-person]')];if(inputs.length){let checked=inputs.filter(x=>x.checked).map(x=>x.dataset.person);if(!checked.length)return false;if(!(l.people||[]).some(p=>checked.includes(p)))return false}return true}
function filter(){state.lines.forEach(l=>l.visible=allowed(l));renderList();preview()}
function reorderById(fromId,toId){if(!fromId||!toId||fromId===toId)return;let from=state.lines.findIndex(x=>x.id===fromId);if(from<0)return;hist();let[line]=state.lines.splice(from,1),to=state.lines.findIndex(x=>x.id===toId);if(to<0)state.lines.push(line);else state.lines.splice(to,0,line);renderList();preview()}
function renderList(){let v=state.lines.filter(x=>x.visible);$('#list').innerHTML=v.length?'':'<p class="empty">No matching lines.</p>';v.forEach(l=>{let i=state.lines.indexOf(l),d=document.createElement('div');d.className='item';d.draggable=true;d.dataset.id=l.id;d.ondragstart=e=>{dragId=l.id;d.classList.add('dragging');e.dataTransfer.effectAllowed='move'};d.ondragend=()=>{dragId=null;d.classList.remove('dragging');document.querySelectorAll('.dragover').forEach(x=>x.classList.remove('dragover'))};d.ondragover=e=>{e.preventDefault();d.classList.add('dragover')};d.ondragleave=()=>d.classList.remove('dragover');d.ondrop=e=>{e.preventDefault();d.classList.remove('dragover');reorderById(dragId,l.id)};
let left=document.createElement('div');left.className='selectcol';let handle=document.createElement('span');handle.className='drag';handle.textContent='⋮⋮';handle.title='Drag to reorder';let ck=document.createElement('input');ck.type='checkbox';ck.checked=l.selected;ck.onchange=()=>{hist();l.selected=ck.checked;preview()};left.append(handle,ck);
let ta=document.createElement('textarea');ta.value=l.edited;ta.onchange=()=>{hist();l.edited=ta.value;preview()};
let ctl=document.createElement('div');ctl.className='controls';for(let[txt,title,fn]of[['↑','Move up',()=>{hist();move(state.lines,i,-1);renderList();preview()}],['↓','Move down',()=>{hist();move(state.lines,i,1);renderList();preview()}],['↺','Restore original',()=>{hist();l.edited=l.original;renderList();preview()}],['✕','Exclude line',()=>{hist();l.selected=false;renderList();preview()}]]){let b=document.createElement('button');b.textContent=txt;b.title=title;b.onclick=fn;ctl.appendChild(b)}d.append(left,ta,ctl);$('#list').appendChild(d)})}
function preview(){let p=$('#preview');p.innerHTML='';p.style.maxWidth=$('#width').value+'px';p.style.padding=$('#chatbg').checked?'8px':'0';p.style.background=$('#chatbg').checked?'rgba(0,0,0,.45)':'transparent';let shown=state.lines.filter(x=>x.visible&&x.selected);shown.forEach(l=>{let d=document.createElement('div');d.className='chat';d.style.fontSize=$('#font').value+'px';if($('#timestamps').checked&&l.ts){let s=document.createElement('span');s.style.color='#aaa';s.textContent=`[${l.ts}] `;d.appendChild(s)}recolor(l,state.mode,$('#self').value.trim()).forEach(g=>{let s=document.createElement('span');s.style.color=g.color;s.textContent=g.text;d.appendChild(s)});p.appendChild(d)});$('#stats').textContent=`${shown.length} selected / ${state.lines.filter(x=>x.visible).length} visible`}
$('#build').onclick=build;$('#apply').onclick=filter;['rp','ooc','system','from','to'].forEach(id=>$('#'+id).onchange=filter);['font','width','timestamps','chatbg'].forEach(id=>$('#'+id).oninput=()=>{$('#fontv').textContent=$('#font').value;preview()});$('#all').onclick=()=>{hist();state.lines.filter(x=>x.visible).forEach(x=>x.selected=true);renderList();preview()};$('#none').onclick=()=>{hist();state.lines.filter(x=>x.visible).forEach(x=>x.selected=false);renderList();preview()};$('#undo').onclick=()=>{if(!undo.length)return;redo.push(snapshot(state.lines));state.lines=restore(undo.pop());renderList();preview()};$('#redo').onclick=()=>{if(!redo.length)return;undo.push(snapshot(state.lines));state.lines=restore(redo.pop());renderList();preview()};$('#save').onclick=()=>{save({source:$('#source').value,self:$('#self').value,mode:$('#mode').value,state});$('#detected').textContent='Project saved in this browser.'};$('#load').onclick=()=>{let x=load();if(!x)return;$('#source').value=x.source;$('#self').value=x.self;$('#mode').value=x.mode;state=x.state;people();filter();$('#detected').textContent='Saved project loaded.'};$('#copy').onclick=async()=>navigator.clipboard.writeText(state.lines.filter(x=>x.visible&&x.selected).map(x=>( $('#timestamps').checked&&x.ts?`[${x.ts}] `:'')+x.edited).join('\n'));$('#png').onclick=()=>png(state.lines.filter(x=>x.visible&&x.selected),opts(),l=>recolor(l,state.mode,$('#self').value.trim()));$('#clear').onclick=()=>{$('#source').value='';state.lines=[];people();filter()};$('#sample').onclick=()=>{$('#source').value=`[20:55:03] ~y~Marisol Lopez says (phone): Zohan?\n[20:55:59] (Phone) * Marisol Lopez has a broken tone of voice.\n[20:57:02] !{#C2A2DA}* Marisol Lopez pinches Jovan’s side.\n[20:57:09] !{#5F5F5F}Marisol Lopez says [low]: Or what?\n[20:57:20] !{#F0F0F0}Jovan Tomic says [low]: I didn't mean that, baby girl, princess.`;$('#mode').value='auto';$('#self').value='Jovan Tomic';build()};