import{parse,parseEditedLine,renderLine}from'./parser.js';
const $=s=>document.querySelector(s),canvas=$('#canvas'),overlay=$('#chatOverlay'),bg=$('#bg');let drag=false,dx=0,dy=0,imgURL='';
function mode(){let m=$('#cmode').value;return m==='auto'?parse($('#chattext').value,'auto',$('#cself').value).mode:m}
function render(){let text=$('#chattext').value,m=mode(),self=$('#cself').value.trim(),lines=text.replace(/\r/g,'').split('\n').filter(x=>x.trim()).map(x=>parseEditedLine(x,m,self));overlay.innerHTML='';overlay.style.width=$('#chatwidth').value+'px';overlay.style.background=`rgba(0,0,0,${+$('#opacity').value/100})`;overlay.style.padding=+$('#opacity').value?'8px':'0';for(let l of lines){let d=document.createElement('div');d.className='chat';d.style.fontSize=$('#cfont').value+'px';if($('#ctimestamps').checked&&l.ts){let s=document.createElement('span');s.style.color='#aaa';s.textContent=`[${l.ts}] `;d.appendChild(s)}renderLine(l,m,self).forEach(g=>{let s=document.createElement('span');s.style.color=g.color;s.textContent=g.text;d.appendChild(s)});overlay.appendChild(d)}$('#cfontv').textContent=$('#cfont').value;$('#chatwidthv').textContent=$('#chatwidth').value;$('#opacityv').textContent=$('#opacity').value+'%'}
function size(){let[w,h]=$('#preset').value.split('x').map(Number);canvas.style.width=w+'px';canvas.style.height=h+'px';$('#canvasinfo').textContent=`${w} × ${h}`;scale()}
function scale(){let shell=document.querySelector('.canvas-shell'),w=parseInt(canvas.style.width)||1920;let s=Math.min(1,(shell.clientWidth-4)/w);canvas.style.transform=`scale(${s})`;canvas.parentElement.style.height=(parseInt(canvas.style.height)*s)+'px'}
function fit(){bg.style.objectFit='contain'}
$('#image').onchange=e=>{let f=e.target.files[0];if(!f)return;if(imgURL)URL.revokeObjectURL(imgURL);imgURL=URL.createObjectURL(f);bg.src=imgURL;bg.style.display='block';$('#empty').style.display='none';fit()}
$('#removebg').onclick=()=>{bg.removeAttribute('src');bg.style.display='none';$('#empty').style.display='grid';if(imgURL)URL.revokeObjectURL(imgURL);imgURL=''}
$('#fit').onclick=fit;$('#centerchat').onclick=()=>{overlay.style.left='35px';overlay.style.top='35px'}
;['chattext','cmode','cself','cfont','chatwidth','opacity','ctimestamps'].forEach(id=>$('#'+id).addEventListener(id==='chattext'?'input':'change',render));$('#cfont').oninput=render;$('#chatwidth').oninput=render;$('#opacity').oninput=render;$('#preset').onchange=size;
overlay.addEventListener('pointerdown',e=>{drag=true;overlay.setPointerCapture(e.pointerId);dx=e.clientX-overlay.getBoundingClientRect().left;dy=e.clientY-overlay.getBoundingClientRect().top});
overlay.addEventListener('pointermove',e=>{if(!drag)return;let r=canvas.getBoundingClientRect(),sx=canvas.offsetWidth/r.width,sy=canvas.offsetHeight/r.height;let x=(e.clientX-r.left)*sx-dx*sx,y=(e.clientY-r.top)*sy-dy*sy;overlay.style.left=Math.max(0,Math.min(canvas.offsetWidth-overlay.offsetWidth,x))+'px';overlay.style.top=Math.max(0,Math.min(canvas.offsetHeight-overlay.offsetHeight,y))+'px'});
overlay.addEventListener('pointerup',()=>drag=false);
$('#export').onclick=async()=>{let W=canvas.offsetWidth,H=canvas.offsetHeight,c=document.createElement('canvas');c.width=W;c.height=H;let ctx=c.getContext('2d');ctx.fillStyle='#15191e';ctx.fillRect(0,0,W,H);if(bg.src){let iw=bg.naturalWidth,ih=bg.naturalHeight,s=Math.min(W/iw,H/ih),dw=iw*s,dh=ih*s;ctx.drawImage(bg,(W-dw)/2,(H-dh)/2,dw,dh)}let fs=+$('#cfont').value,lh=Math.ceil(fs*1.27),x0=overlay.offsetLeft+(+$('#opacity').value?8:0),y=overlay.offsetTop+(+$('#opacity').value?8:0),maxw=+$('#chatwidth').value-(+$('#opacity').value?16:0),m=mode(),self=$('#cself').value.trim();ctx.font=`700 ${fs}px Arial`;ctx.textBaseline='top';ctx.lineJoin='round';ctx.lineWidth=3;let lines=$('#chattext').value.replace(/\r/g,'').split('\n').filter(x=>x.trim());for(let raw of lines){let l=parseEditedLine(raw,m,self),segs=[];if($('#ctimestamps').checked&&l.ts)segs.push({text:`[${l.ts}] `,color:'#aaa'});segs.push(...renderLine(l,m,self));let rows=[[]],rw=0;for(let s of segs)for(let part of s.text.split(/(\s+)/)){if(!part)continue;let pw=ctx.measureText(part).width;if(rw+pw>maxw&&rows.at(-1).length&&!/^\s+$/.test(part)){rows.push([]);rw=0}rows.at(-1).push({text:part,color:s.color});rw+=pw}if(+$('#opacity').value){ctx.fillStyle=`rgba(0,0,0,${+$('#opacity').value/100})`;ctx.fillRect(overlay.offsetLeft,y-8,+$('#chatwidth').value,rows.length*lh+16)}for(let row of rows){let x=x0;for(let s of row){ctx.strokeStyle='#000';ctx.strokeText(s.text,x,y);ctx.fillStyle=s.color;ctx.fillText(s.text,x,y);x+=ctx.measureText(s.text).width}y+=lh}}let blob=await new Promise(r=>c.toBlob(r,'image/png'));let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='gtaw-composed-screenshot.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
let saved=sessionStorage.getItem('gtawComposerChat');if(saved)try{let d=JSON.parse(saved);$('#chattext').value=d.text||'';$('#cmode').value=d.mode||'auto';$('#cself').value=d.self||'';$('#ctimestamps').checked=d.timestamps!==false;if(d.font)$('#cfont').value=d.font}catch{}size();render();addEventListener('resize',scale);