import{parse,parseEditedLine,renderLine}from'./parser.js';
const $=s=>document.querySelector(s),canvas=$('#canvas'),overlay=$('#chatOverlay'),bg=$('#bg');let drag=false,dx=0,dy=0,imgURL='';
function mode(){let m=$('#cmode').value;return m==='auto'?parse($('#chattext').value,'auto',$('#cself').value).mode:m}
function render(){let text=$('#chattext').value,m=mode(),self=$('#cself').value.trim(),lines=text.replace(/\r/g,'').split('\n').filter(x=>x.trim()).map(x=>parseEditedLine(x,m,self));overlay.innerHTML='';overlay.style.width=$('#chatwidth').value+'px';overlay.style.background=`rgba(0,0,0,${+$('#opacity').value/100})`;overlay.style.padding=+$('#opacity').value?'8px':'0';for(let l of lines){let d=document.createElement('div');d.className='chat';d.style.fontSize=$('#cfont').value+'px';if($('#ctimestamps').checked&&l.ts){let s=document.createElement('span');s.style.color='#aaa';s.textContent=`[${l.ts}] `;d.appendChild(s)}renderLine(l,m,self).forEach(g=>{let s=document.createElement('span');s.style.color=g.color;s.textContent=g.text;d.appendChild(s)});overlay.appendChild(d)}$('#cfontv').textContent=$('#cfont').value;$('#chatwidthv').textContent=$('#chatwidth').value;$('#opacityv').textContent=$('#opacity').value+'%'}
function size(){let[w,h]=$('#preset').value.split('x').map(Number);canvas.style.width=w+'px';canvas.style.height=h+'px';$('#canvasinfo').textContent=`${w} × ${h}`;scale()}
function scale(){let shell=document.querySelector('.canvas-shell'),w=parseInt(canvas.style.width)||1920,h=parseInt(canvas.style.height)||1080,aw=Math.max(1,shell.clientWidth-8),ah=Math.max(1,shell.clientHeight-8),s=Math.min(aw/w,ah/h);canvas.style.transform=`scale(${s})`;canvas.parentElement.style.height='auto'}
function fit(){bg.style.objectFit=$('#imagemode').value||'cover'}
$('#image').onchange=async e=>{let f=e.target.files[0];if(!f)return;if(imgURL)URL.revokeObjectURL(imgURL);imgURL=URL.createObjectURL(f);bg.src=imgURL;bg.style.display='block';$('#empty').style.display='none';fit();await saveImage(f);saveComposer()}
$('#removebg').onclick=async()=>{bg.removeAttribute('src');bg.style.display='none';$('#empty').style.display='grid';if(imgURL)URL.revokeObjectURL(imgURL);imgURL='';await saveImage(null);saveComposer()}
$('#imagemode').onchange=()=>{fit();};$('#centerchat').onclick=()=>{overlay.style.left='35px';overlay.style.top='35px'}
;['chattext','cmode','cself','cfont','chatwidth','opacity','ctimestamps'].forEach(id=>$('#'+id).addEventListener(id==='chattext'?'input':'change',render));$('#cfont').oninput=render;$('#chatwidth').oninput=render;$('#opacity').oninput=render;$('#preset').onchange=size;
overlay.addEventListener('pointerdown',e=>{drag=true;overlay.setPointerCapture(e.pointerId);dx=e.clientX-overlay.getBoundingClientRect().left;dy=e.clientY-overlay.getBoundingClientRect().top});
overlay.addEventListener('pointermove',e=>{if(!drag)return;let r=canvas.getBoundingClientRect(),sx=canvas.offsetWidth/r.width,sy=canvas.offsetHeight/r.height;let x=(e.clientX-r.left)*sx-dx*sx,y=(e.clientY-r.top)*sy-dy*sy;overlay.style.left=Math.max(0,Math.min(canvas.offsetWidth-overlay.offsetWidth,x))+'px';overlay.style.top=Math.max(0,Math.min(canvas.offsetHeight-overlay.offsetHeight,y))+'px'});
overlay.addEventListener('pointerup',()=>drag=false);
$('#export').onclick=async()=>{let W=canvas.offsetWidth,H=canvas.offsetHeight,c=document.createElement('canvas');c.width=W;c.height=H;let ctx=c.getContext('2d');ctx.fillStyle='#15191e';ctx.fillRect(0,0,W,H);if(bg.src){let iw=bg.naturalWidth,ih=bg.naturalHeight,cover=$('#imagemode').value==='cover',s=cover?Math.max(W/iw,H/ih):Math.min(W/iw,H/ih),dw=iw*s,dh=ih*s;ctx.drawImage(bg,(W-dw)/2,(H-dh)/2,dw,dh)}let fs=+$('#cfont').value,lh=Math.ceil(fs*1.27),x0=overlay.offsetLeft+(+$('#opacity').value?8:0),y=overlay.offsetTop+(+$('#opacity').value?8:0),maxw=+$('#chatwidth').value-(+$('#opacity').value?16:0),m=mode(),self=$('#cself').value.trim();ctx.font=`700 ${fs}px Arial`;ctx.textBaseline='top';ctx.lineJoin='round';ctx.lineWidth=3;let lines=$('#chattext').value.replace(/\r/g,'').split('\n').filter(x=>x.trim());for(let raw of lines){let l=parseEditedLine(raw,m,self),segs=[];if($('#ctimestamps').checked&&l.ts)segs.push({text:`[${l.ts}] `,color:'#aaa'});segs.push(...renderLine(l,m,self));let rows=[[]],rw=0;for(let s of segs)for(let part of s.text.split(/(\s+)/)){if(!part)continue;let pw=ctx.measureText(part).width;if(rw+pw>maxw&&rows.at(-1).length&&!/^\s+$/.test(part)){rows.push([]);rw=0}rows.at(-1).push({text:part,color:s.color});rw+=pw}if(+$('#opacity').value){ctx.fillStyle=`rgba(0,0,0,${+$('#opacity').value/100})`;ctx.fillRect(overlay.offsetLeft,y-8,+$('#chatwidth').value,rows.length*lh+16)}for(let row of rows){let x=x0;for(let s of row){ctx.strokeStyle='#000';ctx.strokeText(s.text,x,y);ctx.fillStyle=s.color;ctx.fillText(s.text,x,y);x+=ctx.measureText(s.text).width}y+=lh}}let blob=await new Promise(r=>c.toBlob(r,'image/png'));let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='gtaw-composed-screenshot.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};


const COMPOSER_KEY='gtawComposerStateV1';
function openDB(){return new Promise((resolve,reject)=>{let q=indexedDB.open('gtawChatToolDB',1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains('files'))q.result.createObjectStore('files')};q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}
async function saveImage(blob){try{let db=await openDB(),tx=db.transaction('files','readwrite');blob?tx.objectStore('files').put(blob,'composerBackground'):tx.objectStore('files').delete('composerBackground');await new Promise((r,j)=>{tx.oncomplete=r;tx.onerror=()=>j(tx.error)});db.close()}catch(e){console.warn('Could not save screenshot',e)}}
async function loadImage(){try{let db=await openDB(),tx=db.transaction('files','readonly'),q=tx.objectStore('files').get('composerBackground'),blob=await new Promise((r,j)=>{q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});db.close();if(blob){if(imgURL)URL.revokeObjectURL(imgURL);imgURL=URL.createObjectURL(blob);bg.src=imgURL;bg.style.display='block';$('#empty').style.display='none'}}catch(e){console.warn('Could not restore screenshot',e)}}
function composerSnapshot(){return{text:$('#chattext').value,mode:$('#cmode').value,self:$('#cself').value,font:$('#cfont').value,chatwidth:$('#chatwidth').value,opacity:$('#opacity').value,timestamps:$('#ctimestamps').checked,preset:$('#preset').value,imagemode:$('#imagemode').value,left:overlay.style.left||'35px',top:overlay.style.top||'35px'}}
function saveComposer(){try{localStorage.setItem(COMPOSER_KEY,JSON.stringify(composerSnapshot()))}catch(e){console.warn('Could not save composer workspace',e)}}
async function restoreComposer(){
 let d;try{d=JSON.parse(localStorage.getItem(COMPOSER_KEY)||'null')}catch{}
 if(d){$('#chattext').value=d.text||'';$('#cmode').value=d.mode||'auto';$('#cself').value=d.self||'';$('#cfont').value=d.font||'16';$('#chatwidth').value=d.chatwidth||'700';$('#opacity').value=d.opacity||'0';$('#ctimestamps').checked=d.timestamps!==false;$('#preset').value=d.preset||'1920x1080';$('#imagemode').value=d.imagemode||'cover';overlay.style.left=d.left||'35px';overlay.style.top=d.top||'35px'}
 let incoming;try{incoming=JSON.parse(localStorage.getItem('gtawComposerIncoming')||'null')}catch{}
 if(incoming){$('#chattext').value=incoming.text||$('#chattext').value;$('#cmode').value=incoming.mode||$('#cmode').value;$('#cself').value=incoming.self||$('#cself').value;$('#ctimestamps').checked=incoming.timestamps!==false;if(incoming.font)$('#cfont').value=incoming.font;localStorage.removeItem('gtawComposerIncoming')}
 await loadImage();size();fit();render();saveComposer()
}
document.addEventListener('input',e=>{if(e.target.closest('main'))saveComposer()});
document.addEventListener('change',e=>{if(e.target.closest('main'))setTimeout(saveComposer,0)});
overlay.addEventListener('pointerup',saveComposer);
$('#centerchat').addEventListener('click',()=>setTimeout(saveComposer,0));
$('#newproject').onclick=async()=>{if(confirm('Start a new project? This clears saved Formatter and Screenshot Composer progress.')){localStorage.removeItem(COMPOSER_KEY);localStorage.removeItem('gtawChatToolFormatterV1');localStorage.removeItem('gtawComposerIncoming');await saveImage(null);location.href='index.html'}};
addEventListener('beforeunload',saveComposer);
restoreComposer();addEventListener('resize',scale);
