export const C={purple:'#C2A2DA',white:'#F0F0F0',ooc:'#696969',yellow:'#FFFF00',pink:'#FF00C3',grey:'#B8B8B8'};
const tokenRE=/!\{#([0-9A-Fa-f]{6})\}|(~[yrgbpows]~)/g;const gta={'~y~':'#FFFF00','~r~':'#FF0000','~g~':'#00FF00','~b~':'#0000FF','~p~':'#A020F0','~o~':'#FFA500','~w~':'#FFFFFF'};
export function detect(s){return /!\{#[0-9a-f]{6}\}/i.test(s)?'ucp':'assistant'}
function ucp(body){let a=[],last=0,color=C.white,m;tokenRE.lastIndex=0;while((m=tokenRE.exec(body))){if(m.index>last)a.push({text:body.slice(last,m.index),color});if(m[1])color='#'+m[1].toUpperCase();else if(gta[m[2]?.toLowerCase()])color=gta[m[2].toLowerCase()];last=tokenRE.lastIndex}if(last<body.length)a.push({text:body.slice(last),color});if(/^\s*\(Phone\)\s*\*/i.test(body)&&!body.includes('!{#'))return[{text:body,color:C.purple}];return a.length?a:[{text:body,color}]}
function assistant(body,self){if(/^\s*(?:\(Phone\)\s*)?\*\s+/i.test(body)||/^\s*>\s+/.test(body))return[{text:body,color:C.purple}];if(/^\s*\(\(.*\)\)\s*$/.test(body))return[{text:body,color:C.ooc}];if(/^\s*\[!\]\s*/.test(body))return[{text:'[!] ',color:C.pink},{text:body.replace(/^\s*\[!\]\s*/,''),color:C.white}];if(/\bsays(?:\s+\[[^\]]+\])?\s+\(phone\):/i.test(body)){let sp=(body.match(/^\s*(.+?)\s+says/i)||[])[1]||'';return[{text:body,color:self&&sp.toLowerCase()===self.toLowerCase()?C.white:C.yellow}]}if(/^\s*\[PHONE\]/i.test(body))return[{text:body,color:C.yellow}];if(/^\s*\([^)]*\)\s+Message\s+(?:from|sent to)/i.test(body))return[{text:body,color:'#D9D9D9'}];return[{text:body,color:C.white}]}
function typeOf(p){if(/^\s*\(\(/.test(p))return'ooc';if(/^\s*(?:\(Phone\)\s*)?\*|^\s*>/.test(p))return'emote';if(/\bsays\b/i.test(p))return'speech';if(/Message (?:from|sent to)/i.test(p))return'message';return'system'}
function cleanName(s){return(s||'').replace(/^\[!\]\s*/,'').trim()}
function peopleOf(p){let out=[];let speech=p.match(/^\s*(?:\[!\]\s*)?(.+?)\s+says(?:\s+\[[^\]]+\])?(?:\s+\(phone\))?:/i);if(speech)out.push(cleanName(speech[1]));let emote=p.match(/^\s*(?:\(Phone\)\s*)?(?:\*|>)\s+([A-Z][\w'-]+(?:\s+[A-Z][\w'-]+)+)\b/);if(emote)out.push(cleanName(emote[1]));return[...new Set(out.filter(Boolean))]}
function messagePersonOf(p){let m=p.match(/\bMessage\s+(?:from|sent to)\s+([^:]+):/i);return m?cleanName(m[1]):''}
export function parse(text,mode='auto',self=''){const actual=mode==='auto'?detect(text):mode;let lines=text.replace(/\r/g,'').split('\n').filter(Boolean).map((raw,i)=>{let ts='',body=raw,m=body.match(/^\s*\[(\d{1,2}:\d{2}(?::\d{2})?)\]\s*/);if(m){ts=m[1];body=body.slice(m[0].length)}let seg=actual==='ucp'?ucp(body):assistant(body,self),plain=seg.map(x=>x.text).join(''),people=peopleOf(plain),messagePerson=messagePersonOf(plain);return{id:crypto.randomUUID?.()||String(Date.now()+i),raw,ts,body,original:plain,edited:plain,segments:seg,type:typeOf(plain),speaker:people[0]||'',people,messagePerson,selected:true}});return{mode:actual,lines}}
export function recolor(line,mode,self){if(line.edited===line.original)return line.segments;return mode==='ucp'?[{text:line.edited,color:line.type==='emote'?C.purple:line.type==='ooc'?C.ooc:C.white}]:assistant(line.edited,self)}